#pragma once

const char *board_empty_grid =
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          ";

const char *board_with_first_piece =
  "          "
  "   IIII   "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          ";

const char *board_with_first_piece_r1 =
  "     I    "
  "     I    "
  "     I    "
  "     I    "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          ";

const char *board_with_first_piece_r1_drop_and_drop_six_more =
  "          "
  "   IIII   "
  "          "
  "          "
  "   ZZ     "
  "    ZZ    "
  "    T     "
  "   TTT    "
  "    SS    "
  "   SS     "
  "    OO    "
  "    OO    "
  "     L    "
  "   LLL    "
  "   J      "
  "   JJJ    "
  "     I    "
  "     I    "
  "     I    "
  "     I    ";

const char *board_with_first_piece_r2 =
  "          "
  "          "
  "   IIII   "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          ";

const char *board_with_first_piece_r3 =
  "    I     "
  "    I     "
  "    I     "
  "    I     "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          ";

const char *board_with_first_piece_far_left =
  "          "
  "IIII      "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          ";

const char *board_with_first_piece_far_left_dropped_1 =
  "          "
  "          "
  "IIII      "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          ";
const char *board_with_first_piece_far_left_dropped_2 =
  "          "
  "          "
  "          "
  "IIII      "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          ";

const char *board_with_first_piece_far_left_dropped_entirely =
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "IIII      ";

const char *board_with_first_piece_far_left_dropped_new_piece_showing =
  "   J      "
  "   JJJ    "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "IIII      ";

const char *board_with_second_piece_dropped =
  "     L    "
  "   LLL    "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "   J      "
  "   JJJ    "
  "IIII      ";

const char *board_with_first_piece_far_right =
  "          "
  "      IIII"
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          ";

const char *board0_grid =
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "T  OOS    "
  "TTZOOSS   "
  "TZZTZZS   "
  "SZLTTZZL  "
  "SSLTOOJL  "
  "JSLLOOJLL "
  "JJJLTJJZI "
  "ILLLTTZZI "
  "IOOSTIZZI ";

const char *board1_grid =
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "          "
  "T  OOS    "
  "TTZOOSS   "
  "TZZTZZS   "
  "SZLTTZZL  "
  "SSLTOOJL  "
  "JSLLOOJLLI"
  "JJJLTJJZII"
  "ILLLTTZZII"
  "IOOSTIZZII";

